name: Build Windows

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  QT_MIRROR: https://mirrors.ocf.berkeley.edu/qt/
  PROD_AGW_PUBLIC_KEY: ""
  PROD_S3_ENDPOINT: ""
  FALLBACK_S3_ENDPOINT: ""
  DEV_AGW_PUBLIC_KEY: ""
  DEV_AGW_ENDPOINT: ""
  DEV_S3_ENDPOINT: ""
  FREE_V2_ENDPOINT: ""
  PREM_V1_ENDPOINT: ""

jobs:
  Build-Windows:
    runs-on: windows-latest

    steps:
    - name: Get sources
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 10

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.10.1
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtremoteobjects qt5compat qtshadertools'
        dir: ${{ runner.temp }}
        setup-python: 'true'
        set-env: 'true'
        aqtversion: '==3.3.0'
        py7zrversion: '==0.22.*'
        extra: '--base ${{ env.QT_MIRROR }}'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: 'x64'

    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: 3.14

    - name: Install conan
      run: pip install "conan==2.28.0"

    - name: Export local recipes
      shell: pwsh
      run: |
        Get-ChildItem -Path recipes -Recurse -Filter conanfile.py | ForEach-Object {
          $dir = $_.DirectoryName
          conan export $dir
        }

    - name: Remove private Conan remote
      shell: pwsh
      run: conan remote remove Rampage 2>$null; conan remote list

    - name: Configure CMake
      shell: pwsh
      run: cmake -S . -B build

    - name: Build
      shell: cmd
      run: cmake --build build --config Release --parallel

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: RampageVPN_Windows_x64
        path: build/client/Release/RampageVPN.exe
        retention-days: 7
